spring:
  main:
    web-application-type: none
  ssl:
    bundle:
      pem:
        client:
          keystore:
            certificate: file:${CERTS_DIR:/certs}/client.crt
            private-key: file:${CERTS_DIR:/certs}/client.pkcs8.pem
          truststore:
            certificate: file:${CERTS_DIR:/certs}/ca.crt
        stranger:
          keystore:
            certificate: file:${CERTS_DIR:/certs}/stranger.crt
            private-key: file:${CERTS_DIR:/certs}/stranger.pkcs8.pem
          truststore:
            certificate: file:${CERTS_DIR:/certs}/ca.crt
  grpc:
    client:
      channels:
        greeter:
          address: ${GRPC_SERVER_ADDRESS:static://localhost:9090}
          negotiation-type: tls
          ssl:
            bundle: client
        stranger:
          address: ${GRPC_SERVER_ADDRESS:static://localhost:9090}
          negotiation-type: tls
          ssl:
            bundle: stranger

logging:
  level:
    io.grpc: INFO
